server:
  port: 8900
spring:
  application:
    name: provider-order-ribbon
user:
  url: http://127.0.0.1:7900/user/
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: provider-order